=== opwvhk/avro-conversions/src/test/resources/opwvhk/avro/json/TestRecord.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "TestCase",
    "description": "Test schema for parsing records.",
    "properties": {
        "bool": {
            "type": "boolean"
        },
        "shortInt": {
            "type": ["integer", "null"],
            "$comment": "bounds are smaller than 2^31-1",
            "minimum": -2000000000,
            "maximum": 2000000000
        },
        "longInt": {
            "type": "integer",
            "$comment": "bounds are between 2^31-1 and 2^63-1",
            "minimum": -9000000000,
            "maximum": 9000000000
        },
        "hugeInt": {
            "type": "integer",
            "$comment": "bounds are larger than 2^63-1",
            "minimum": 0,
            "maximum": 200000000000000000000
        },
        "defaultInt": {
            "type": "integer",
            "default": 42
        },
        "singleFloat": {
            "type": "number",
            "$comment": "bounds have precision < 7",
            "minimum": -999.9,
            "maximum": 999.9
        },
        "doubleFloat": {
            "type": "number",
            "$comment": "bounds have precision >= 7 and < 16",
            "minimum": -9999999.999,
            "maximum": 99999.99999
        },
        "fixedPoint": {
            "type": "number",
            "minimum": -9999999999.999999,
            "maximum": 99999999999.99999
        },
        "choice": {
            "enum": ["yes", "no", "maybe"]
        },
        "date": {
            "type": "string",
            "format": "date"
        },
        "time": {
            "type": "string",
            "format": "time"
        },
        "timestamp": {
            "type": "string",
            "format": "date-time"
        },
        "binary": {
            "contentEncoding": "base64"
        },
        "hexBytes": {
            "contentEncoding": "base16"
        },
        "texts": {
            "items": {
                "type": "string"
            }
        },
        "weirdStuff": {
            "type": ["null", "object"],
            "properties": {
                "explanation": {
                    "type": ["string", "null"],
                    "format": "prose",
                    "default": "Please explain why"
                },
                "fancy": {
                    "type": ["null", "string"],
                    "contentEncoding": "with-emoji"
                },
                "hatseflats": {
                    "type": ["null", "string"],
                    "$comment": "not included"
                },
                "rabbitHole": {
                    "$ref": "#/properties/weirdStuff"
                }
            }
        }
    },
    "required": ["bool", "choice", "texts", "weirdStuff"]
}

=== opwvhk/avro-conversions/src/test/resources/opwvhk/avro/json/TestRecord-full.json
{
    "bool": true,
    "shortInt": 42,
    "longInt": 6789012345,
    "hugeInt": 123456789012345678901,
    "defaultInt": 4242,
    "singleFloat": 123.456,
    "doubleFloat": 1234.56789,
    "fixedPoint": 12345678901.123456,
    "choice": "maybe",
    "date": "2023-04-17",
    "time": "17:08:34.567123",
    "timestamp": "2023-04-17T17:08:34.567123",
    "binary": "SGVsbG8gV29ybGQh",
    "hexBytes": "48656C6C6F20576F726C6421",
    "texts": ["Hello", "World!"],
    "weirdStuff": {
        "explanation": "No reason. I just felt like it.",
        "fancy": "😄! You are on Candid Camera! 📹🍌"
    }
}
